# Generated by Django 5.1.3 on 2024-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_desc', models.TextField()),
                ('slider_btn', models.CharField(max_length=100)),
            ],
        ),
    ]
