# Generated by Django 5.1.3 on 2024-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(default='slides/default.png', upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_btn',
            field=models.CharField(max_length=50),
        ),
    ]
