# Generated by Django 5.1.3 on 2024-11-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0004_slider_slider_image_alter_slider_slider_btn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='message',
            new_name='quote_desc',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='quote_title',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone',
        ),
    ]
