# Generated by Django 5.1.3 on 2024-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0005_rename_message_quote_quote_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_head',
            field=models.CharField(default='Quote', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_sub',
            field=models.CharField(default='Quote', max_length=50),
        ),
    ]
