# Generated by Django 5.1.3 on 2024-11-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0006_quote_quote_head_quote_quote_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_head', models.CharField(max_length=100)),
                ('construction_sub', models.CharField(max_length=50)),
                ('construction_title', models.CharField(max_length=100)),
                ('construction_image', models.ImageField(upload_to='constructions/')),
                ('construction_desc', models.TextField()),
            ],
        ),
    ]
