# Generated by Django 5.1.3 on 2024-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0007_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_head', models.CharField(max_length=100)),
                ('testimonial_sub', models.CharField(max_length=100)),
                ('testimonial_name', models.CharField(max_length=50)),
                ('testimonial_occ', models.CharField(max_length=50)),
                ('testimonial_message', models.TextField()),
            ],
        ),
    ]
