# Generated by Django 5.1.2 on 2024-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_pass',
            field=models.ImageField(upload_to='student/'),
        ),
    ]
